### ISSUE TITLE
Kompatibilita přes Composer

### ISSUE THREAD

**Issue by lukdanek** [fabiancz/linkedin-nette#2]
Ahoj,
bylo by možné zvýšit kompatibilitu i na nette 2.2.x?

Děkuju
Lukáš

**Comment by fabiancz** [comment]
Ahoj, promin notifikace mi trochu zapadla.

Zvysil jsem kompatibilitu na Nette 2.2.*, funguje?

**Comment by fprochazka** [comment]
Nezvýšil jsi kompatibilitu na `nette 2.2.*`, změnil jsi podporu na **jenom** `nette 2.2.*` :)

**Comment by fabiancz** [comment]
Sorry, opraveno. Dik

**Comment by fabiancz** [comment]
Akorat Packagist mi napsal:

Reading composer.json of fabian/linkedin-nette (master)
Importing branch master (dev-master)
Skipped branch master, Invalid package information: 
require.nette/nette : invalid version constraint (Could not parse version constraint >=2.1._: Invalid version string "2.1._")

Nevite, jak to tedy spravne zapsat? Dik.

**Comment by fprochazka** [comment]
Mělo by fungovat `"nette/nette": "~2.1"`

**Comment by fabiancz** [comment]
Aha, tak oprava opravy a uz to snad bude ok. Dik za pomoc.
